version: '3.8'

services:
  database:
    container_name: postgres_db
    image: postgres:alpine
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  backend:
    container_name: fastapi_backend
    image: fastapi-backend:latest
    env_file:
      - .env
    ports:
      - 8080:8080
