name: Deploy Docker image to google cloud run.

on:
  workflow_dispatch

jobs:
  could-run-deploy:
    name: Start a cloud run instance using the latest image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GCP Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Start Cloud Run Deploy
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'hello-cloud-run'
          image: 'gcr.io/cloudrun/hello'

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
